import React, { useState, useEffect } from "react";
import { QRCodeSVG } from "qrcode.react";
const windowElectron = window.electron || null;

const WhatsAppHistory = () => {
  const [qrCode, setQrCode] = useState(null);
  const [status, setStatus] = useState("INITIALIZING");

  useEffect(() => {
    if (!windowElectron) return;

    // Request current status immediately on mount
    windowElectron.ipcRenderer.send("request-whatsapp-status");

    // Named handlers for proper cleanup
    const handleQr = (_event, qr) => {
      setQrCode(qr);
      setStatus("QR_READY");
    };

    const handleStatusUpdate = (_event, newStatus) => {
      setStatus(newStatus);
      if (newStatus === "CONNECTED") {
        setQrCode(null);
      }
    };

    windowElectron.ipcRenderer.on("whatsapp-qr", handleQr);
    windowElectron.ipcRenderer.on("whatsapp-status-update", handleStatusUpdate);

    return () => {
      windowElectron.ipcRenderer.removeListener("whatsapp-qr", handleQr);
      windowElectron.ipcRenderer.removeListener("whatsapp-status-update", handleStatusUpdate);
    };
  }, []);

  return (
    <div className="p-8 space-y-8 bg-[#F8FAFC] min-h-screen font-sans">
      {/* Premium Light Header */}
      <div className="flex justify-between items-center border-b border-slate-200 pb-4">
        <div>
          <h2 className="text-2xl font-black text-slate-900 tracking-tight">
            WhatsApp Gateway System
          </h2>
          <p className="text-xs text-slate-500 mt-1">
            Authenticate session keys and trace network dispatches locally.
          </p>
        </div>

        <span
          className={`text-xs px-3 py-1 rounded-full font-bold uppercase border tracking-wider ${
            status === "CONNECTED"
              ? "bg-emerald-50 text-emerald-600 border-emerald-200"
              : status === "QR_READY"
                ? "bg-amber-50 text-amber-600 border-amber-200 animate-pulse"
                : "bg-slate-100 text-slate-600 border-slate-200"
          }`}
        >
          • System: {status}
        </span>
      </div>

      <div className="max-w-4xl bg-white border border-slate-200 p-8 rounded-3xl shadow-sm grid grid-cols-1 md:grid-cols-2 gap-8 items-center">
        {/* Left Side: Dynamic QR Slot */}
        <div className="w-full aspect-square bg-slate-50 border border-slate-200 rounded-2xl flex flex-col items-center justify-center p-6 text-center relative overflow-hidden">
          {status === "CONNECTED" ? (
            <div className="space-y-2">
              <span className="text-4xl">✅</span>
              <h3 className="text-base font-bold text-slate-900">
                Device Fully Linked
              </h3>
              <p className="text-xs text-slate-400">
                Automated messaging triggers are armed and live.
              </p>
            </div>
          ) : qrCode ? (
            <div className="bg-white p-4 rounded-xl shadow-sm border border-slate-100">
              {/* Rendered locally (offline) — the WhatsApp pairing token must
                  never be sent to a third-party QR service. */}
              <QRCodeSVG
                value={qrCode}
                size={208}
                level="M"
                className="w-52 h-52 select-none"
                title="WhatsApp linking QR code"
              />
              <p className="text-[10px] text-slate-400 mt-3 font-medium">
                Scan code to authorize session
              </p>
            </div>
          ) : (
            <div className="space-y-3">
              <div className="w-8 h-8 border-4 border-blue-600 border-t-transparent rounded-full animate-spin mx-auto"></div>
              <p className="text-xs font-bold text-slate-700">
                Booting WhatsApp Kernel...
              </p>
              <p className="text-[10px] text-slate-400 max-w-[180px] mx-auto">
                Initializing chromium background driver socket layers.
              </p>
            </div>
          )}
        </div>

        {/* Right Side: Informational Context */}
        <div className="space-y-4">
          <h3 className="text-base font-black text-slate-900 tracking-tight">
            Link Gym Owner WhatsApp Device
          </h3>
          <p className="text-xs text-slate-500 leading-relaxed">
            Open WhatsApp on your mobile phone, tap{" "}
            <span className="font-bold text-slate-800">Linked Devices</span>,
            and scan this secure dynamic token matrix generated by SENOVA
            Digital Labs core service layer.
          </p>

          <div className="bg-slate-50 border border-slate-100 rounded-xl p-4 text-[11px] text-slate-400 font-mono space-y-1">
            <p>• Driver Node: Local Auth Isolation</p>
            <p>• Hook Stream: Electron IPC Bridge</p>
            <p>• Target Domain: multi-device secure loop</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default WhatsAppHistory;
